# @see https://symfony.com/doc/current/configuration/environment_variables.html#environment-variable-processors
parameters:
  env(SAML_SP_CRT_FILE): '%kernel.project_dir%/saml/sp/sp.crt'
  env(SAML_SP_KEY_FILE): '%kernel.project_dir%/saml/sp/sp.key'
  env(SAML_IDP_CONFIG_FILE): ~
  env(SAML_IDP_CRT_FILE): '%kernel.project_dir%/saml/idp/idp.crt'
  saml_sp_crt: '%env(file:resolve:SAML_SP_CRT_FILE)%'
  saml_sp_key: '%env(file:resolve:SAML_SP_KEY_FILE)%'
  saml_idp_config_file: '%env(resolve:SAML_IDP_CONFIG_FILE)%'
  saml_idp_entity_id: 'https://simplesamlphp.srvitkhulk.itkdev.dk/simplesaml/saml2/idp/metadata.php'
  saml_idp_single_sign_on_service_url: 'https://simplesamlphp.srvitkhulk.itkdev.dk/simplesaml/saml2/idp/SSOService.php'
  saml_idp_single_logout_service_url: 'https://simplesamlphp.srvitkhulk.itkdev.dk/simplesaml/saml2/idp/SingleLogoutService.php'
  saml_idp_crt: '%env(file:resolve:SAML_IDP_CRT_FILE)%'


kontrolgruppen_core:
    # Default value for ProcessType.netDefaultValue
    net_default_value: .7


    exports:
        - Kontrolgruppen\CoreBundle\Export\KL\Export

    saml:

        php_saml_settings:
            # https://github.com/onelogin/php-saml#settings
            strict:              true
            debug:               true
            # baseurl:             '%base_url%'
            sp:
                entityId: '%base_url%'
                assertionConsumerService:
                    url:                 '%base_url%/saml/acs'
                    binding:             'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
                # attributeConsumingService:
                #     serviceName:         SP test
                #     serviceDescription:  Test Service
                #     requestedAttributes:
                #         -
                #             name:
                #             isRequired:
                #             nameFormat:
                #             friendlyName:
                #             attributeValue:
                singleLogoutService:
                    url:                 '%base_url%/saml/sls'
                    binding:             'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
                NameIDFormat:        'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress'
                x509cert: '%saml_sp_crt%'
                privateKey: '%saml_sp_key%'

            _idp:
                entityId: '%saml_idp_entity_id%'
                singleSignOnService:
                    url:                 '%saml_idp_single_sign_on_service_url'
                    binding:             'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
                singleLogoutService:
                    url: '%saml_idp_single_logout_service_url%'
                    responseUrl:         ''
                    binding:             'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
                x509cert: '%saml_idp_crt%'

            idp: '%saml_idp_config_file%'

            # Advanced settings (https://github.com/onelogin/php-saml#settings)
            compress:
                requests:            true
                responses:           true
            security:
                nameIdEncrypted: false
                authnRequestsSigned: false
                logoutRequestSigned: false
                logoutResponseSigned: false
                signMetadata: false
                wantMessagesSigned: false
                wantAssertionsEncrypted: false
                wantAssertionsSigned: false
                wantNameId:          true
                wantNameIdEncrypted: false
                requestedAuthnContext: true
                wantXMLValidation:   true
                relaxDestinationValidation: false
                signatureAlgorithm:  http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
                digestAlgorithm:     http://www.w3.org/2001/04/xmlenc#sha256
                lowercaseUrlencoding: false
            contactPerson:
                technical:
                    givenName: ITK Development
                    emailAddress: itk-dev@aarhus.dk
                support:
                    givenName: ITK Development
                    emailAddress: itk-dev@aarhus.dk
            organization:
                en-US:
                    name: Kontrolgruppen
                    displayname: Kontrolgruppen
                    url: https://kontrolgruppen.example.com

            user_roles:
                attribute: http://schemas.xmlsoap.org/claims/Group
                # Map from ADFS stuff to Symfony roles
                fields:
                    # Common Name
                    CN:
                        # Value: Role(s)
                        GG-Rolle-Kontrolsystem-Admin: ROLE_ADMIN
                        GG-Rolle-Kontrolsystem-Sagsbehandler: ROLE_SAGSBEHANDLER

                        # DG-Right-Kontrolsystem-Admin: ROLE_ADMIN
                        # DG-Right-Kontrolsystem-Sagsbehandler: ROLE_SAGSBEHANDLER
