security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            # id: fos_user.user_provider.username
            id: Kontrolgruppen\CoreBundle\Security\SAMLUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            user_checker: security.user_checker
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true

            guard:
                authenticators:
                    - Kontrolgruppen\CoreBundle\Security\SAMLAuthenticator
                    - Kontrolgruppen\CoreBundle\Security\CliLoginTokenAuthenticator
                entry_point: Kontrolgruppen\CoreBundle\Security\SAMLAuthenticator

    access_control:
        - { path: ^/saml, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
