security:
    role_hierarchy:
        ROLE_BI:          ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_BI]

    providers:
        saml:
            id: Kontrolgruppen\CoreBundle\Security\SAMLUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            guard:
                authenticators:
                    - Kontrolgruppen\CoreBundle\Security\SAMLAuthenticator
                    - Kontrolgruppen\CoreBundle\Security\CliLoginTokenAuthenticator
                entry_point: Kontrolgruppen\CoreBundle\Security\SAMLAuthenticator

    access_control:
        - { path: ^/saml, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/bi/, role: ROLE_BI }
        - { path: ^/, role: ROLE_USER }
